### ISSUE TITLE
bitcoind -conf

### ISSUE THREAD

**Issue by AustinDeric** [freewil/bitcoin-testnet-box#20]
In the Makefile, i expected the bitcoind command for each node to point to its custom bitcoin.conf file. However the original only points to the data directory. 

Original (only points to the data file location):
`$(BITCOIND) $(B1) -daemon`
`$(BITCOIND) $(B2) -daemon`

Expected (points each node to .conf file):
`$(BITCOIND) $(B1) -conf=1/bitcoin.conf -daemon`
`$(BITCOIND) $(B2) -conf=2/bitcoin.conf -daemon`

How does the original command know where the .conf file is located? I am trying the -conf method and i will post the results.  Not really an issue, because i am still analyzing this repo for use. My apologies if i am posting this in the wrong location, i will move it to a better place or delete it if requested.  

Thank you for this resource!

(UPDATE)
my getinfo looks exactly like the presented example, so the only conclusion i come to is that the -datadir flag also point the bitcoind to the bitcoin.conf file for the respective node.  If anyone agrees i will close this issue. Thanks again.

{
  "version": 129900,
  "protocolversion": 70013,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 1,
  "proxy": "",
  "difficulty": 4.656542373906925e-10,
  "testnet": false,
  "keypoololdest": 1464793025,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}
{
  "version": 129900,
  "protocolversion": 70013,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 1,
  "proxy": "",
  "difficulty": 4.656542373906925e-10,
  "testnet": false,
  "keypoololdest": 1464793673,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

**Comment by freewil** [comment]
> my getinfo looks exactly like the presented example, so the only conclusion i come to is that the -datadir flag also point the bitcoind to the bitcoin.conf file for the respective node. If anyone agrees i will close this issue. Thanks again.

Yes, originally `bitcoind` only had the `-datadir` option so, so that is where it will look for the `.conf` files, unless you specify a separate location with `-conf`.
