### ISSUE TITLE
how to determine the address of a node

### ISSUE THREAD

**Issue by s-matthew-english** [freewil/bitcoin-testnet-box#21]
Hi, 

So I'm running this docker* container to create a local testnet for purposes of doing a bit of bitcoin development, actually what I want to do is run [abe](https://github.com/bitcoin-abe/bitcoin-abe) on the local testnet so I can explore transaction in a database. 

anyway, when I run the command `make send ADDRESS=mxwPtt399zVrR62ebkTWL4zbnV1ASdZBQr AMOUNT=10` the bitcoins just disappear... I even minded new blocks to see if maybe the transactions weren't processed but that isn't it either. 

I conjecture that this is because that address isn't associated with my node 2, so then my question is:

how can I determine the actual addresses of my nodes? 

*Well actually I'm running the one of c0achmcguirk/bitcoin-dev-box which is a fork of this- but he doesn't have an issues tab- what's up with that?

**Comment by freewil** [comment]
#19 has been merged
