### ISSUE TITLE
password for user 'tester' ?

### ISSUE THREAD

**Issue by buzai** [freewil/bitcoin-testnet-box#26]
$sudo docker run -t -i -p 19001:19001 -p 19011:19011 freewil/bitcoin-testnet-box

when i run this ,
i come into this docker cmd,
so i want apt get install vim ,
but it tell me i need some root ?
so i use sudo ,but i dont know the tester user`s password.

**Comment by buzai** [comment]
RUN adduser --disabled-login --gecos "" tester
i think this code let all people user this docker enter this is to be a tester
but tester is a nologined user ,so ...

**Comment by zyfdegh** [comment]
+1 Same problem, I think it's unnecessary to add a new user called `tester`. It's OK to use `root`. I'll create a PR to simplify Dockerfile. @buzai

**Comment by buzai** [comment]
@zyfdegh thank u very much

**Comment by freewil** [comment]
There is discussion in #27 on whether user `tester` is necessary.

If I understand the issue correctly - you want to install additional software and/or modify the config from inside the docker container. My suggestion would be to modify the files from outside docker and then build the image/start the container.
