### ISSUE TITLE
Simplify Dockerfile

### ISSUE THREAD

**Issue by zyfdegh** [freewil/bitcoin-testnet-box#27]
I think the layers of the Docker image can be lessen.

Some steps can be merged in Dockerfile, and the user `tester` is unnecessary.

So, in this issue, I want

* Remove unnecessary steps
* Merge commands in one layer

What do you think?

**Comment by freewil** [comment]
>  user tester is unnecessary.

I haven't kept up on the latest container happenings. But last I read, it was still a good practice to use least privilege principle and not use root, even within a container.
