### ISSUE TITLE
bitcoin-qt: not found

### ISSUE THREAD

**Issue by dicristomanuel** [freewil/bitcoin-testnet-box#29]
When running `make start-gui` I get this error `/bin/sh: 1: bitcoin-qt: not found`.

Previous steps taken:
`docker pull freewil/bitcoin-testnet-box`
`docker run -t -i -p 19001:19001 -p 19011:19011 freewil/bitcoin-testnet-box`
and then I try to run start-gui right away.

I have Bitcoin-Qt installed locally, version 0.14.1.

**Comment by freewil** [comment]
It sounds like you may have Bitcoin-Qt installed locally, but are trying to run it within the Docker container that doesn't have it installed?
