### ISSUE TITLE
litecoind integration

### ISSUE THREAD

**Issue by comarius** [freewil/bitcoin-testnet-box#31]
I am trying to make this with litecoin.
prompt$ make start
make: 'start' is up to date.
prompt$ ~/litecoin-testnet-box$ make getinfo
litecoind -datadir=1  getinfo
Error: Command line contains unexpected token 'getinfo', see litecoind -h for a list of options.
Makefile:18: recipe for target 'getinfo' failed
make: *** [getinfo] Error 1
Thank you

**Comment by honglou2001** [comment]
I encounter the same issue, could someone take a look please ?
