### ISSUE TITLE
Docker container not reachable at localhost

### ISSUE THREAD

**Issue by altafan** [freewil/bitcoin-testnet-box#41]
After the last commits, I'm not able to reach the bitcoin daemons curling at `http://admi1:123@localhost:19001/` anymore.
I'm running them with Docker and this happens both if I run a container using the image pulled from the hub or if I build it with the Dockerfile (using commands in the README).
If I checkout to the last merged PR it all works fine instead.

**Comment by freewil** [comment]
Try uncommenting this line in the `bitcoin.conf` files:
`#rpcallowip=0.0.0.0/0`
