### ISSUE TITLE
Command 'make generate' fails on Linux 

### ISSUE THREAD

**Issue by lerai-larak** [freewil/bitcoin-testnet-box#47]
Running the `make generate` command fails. After trying to debug the Makefile I found a hyphen (-) missing before the `generate` argument. Adding this hyphen fixes the issue. I've created a PR for this fix.

**Comment by thevirtuoso1973** [comment]
It seems to be deprecated entirely. https://bitcoin.stackexchange.com/questions/85355/method-not-found-when-i-use-bitcoin-cli-to-generate-blocks-under-regtest-mode

**Comment by freewil** [comment]
This was fixed with https://github.com/freewil/bitcoin-testnet-box/commit/29944ca45207ac517f477d3e97813f83d2ed04b5
