### ISSUE TITLE
Update README.md with the bitcoin-cli version

### ISSUE THREAD

**Issue by IvanVnucec** [freewil/bitcoin-testnet-box#55]
Specify which [bitcoin-cli version](https://bitcoincore.org/bin/) to install in README.md:
```
You must have bitcoind and bitcoin-cli installed on your system and in the path unless running this within a Docker container (see below).
```

**Comment by freewil** [comment]
This is defined here: https://github.com/freewil/bitcoin-testnet-box/blob/6c4df337c5bd003db5f109ef966bd1150d9de8e1/Dockerfile#L16

**Comment by IvanVnucec** [comment]
> This is defined here:
> 
> https://github.com/freewil/bitcoin-testnet-box/blob/6c4df337c5bd003db5f109ef966bd1150d9de8e1/Dockerfile#L16

Yes but what if user doesn't want to run with docker? User doesn't know what bitcoin version to run unless you specify it in the readme.

**Comment by freewil** [comment]
PRs welcome :)
